#!/bin/bash

exec < /dev/tty

###############################################################################
# Warns if you try to merge the "qa" branch on "master                      
###############################################################################
branch_name=$(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3)

message_for_conflict_merge="commit (merge): Merge branch 'qa'"

if [[ $branch_name == "master" ]]; then
    reflog_message=$(git reflog show master -1)

    if [[ $reflog_message =~ $message_for_conflict_merge ]]; then
        read -p "Do you really want to merge the qa branch on master? (y/N) " answer
        if [[ "$answer" != "y" ]]; then
            git reset --merge master@{1}
        fi
    fi
fi
