#!/bin/sh

git diff --cached | ack "debugger"
rc=$?

exec < /dev/tty

if [[ $rc == 0 ]] ; then
  read -p "[pre-commit hook] Do you really want to commit this 'debugger'? (y/N) " yn
  if [ "$yn" != "y" ]; then
      exit 1;
  fi
fi
