#!/bin/sh

exec < /dev/tty

###############################################################################
# Warns if you try to commit a "debugger"
###############################################################################
git diff --cached | ack "debugger"
rc=$?

if [[ $rc == 0 ]]; then
    read -p "Do you really want to commit this 'debugger'? (y/N) " answer
    if [[ "$answer" != "y" ]]; then
        exit 1;
    fi
fi

###############################################################################
# Warns if you try to commit directly to the master branch
###############################################################################
branch_name=$(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3)

if [[ $branch_name == "master" ]]; then
    read -p "Do you really want to commit directly to master? (y/N) " answer
    if [[ "$answer" != "y" ]]; then
        exit 1;
    fi
fi
