#!/bin/bash

exec < /dev/tty

###############################################################################
# Warns if you try to commit a "debugger"
###############################################################################
git diff --cached | grep -q "debugger"
if [[ $? == 0 ]]; then
    read -p "Do you really want to commit this 'debugger'? (y/N) " answer
    if [[ "$answer" != "y" ]]; then
        exit 1;
    fi
fi

###############################################################################
# Warns if you try to commit directly to the qa or master branch
###############################################################################
branch_name=$(git branch | grep "*" | sed "s/\* //")

if [[ $branch_name == "master" || $branch_name == "qa" ]]; then
    read -p "Do you really want to commit directly to $branch_name? (y/N) " answer
    echo "answer = $answer" > answer.txt
    if [[ "$answer" != "y" ]]; then
        exit 1;
    fi
fi
