#!/bin/bash

exec < /dev/tty

warn_if_trying_to_commit() {
    git diff --cached | grep -q "+.*$1"
    if [[ $? == 0 ]]; then
        read -p "Do you really want to commit this '$1'? (y/N) " answer
        if [[ "$answer" != "y" ]]; then
            exit 1;
        fi
    fi
}

warn_if_trying_to_commit "debugger"
warn_if_trying_to_commit "<<<<<<< HEAD"

###############################################################################
# Warns if you try to commit directly to the qa or master branch
###############################################################################
branch_name=$(git branch | grep "*" | sed "s/\* //")

if [[ $branch_name == "master" || $branch_name == "qa" ]]; then
    read -p "Do you really want to commit directly to $branch_name? (y/N) " answer
    if [[ "$answer" != "y" ]]; then
        exit 1;
    fi
fi
